# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
